POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTZiZWI0My1lNGEzLTQ3N2MtOWVkOS1hYTZmMTlkZTM3ZmMiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTk4NDAxNX0.1tHqWse0iNRHWaTcydbRcIHIzsFaYVcAIHEW2eTVaBM

{
  "title": "Curso de React"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/b0739931-4098-460f-8950-ed8585bfc1a3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTZiZWI0My1lNGEzLTQ3N2MtOWVkOS1hYTZmMTlkZTM3ZmMiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTk4NDAxNX0.1tHqWse0iNRHWaTcydbRcIHIzsFaYVcAIHEW2eTVaBM

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Antonio88@live.com",
  "password": "123456"
}